{{- if .Values.services.nginx.noSSL.create -}}
{{- if .Values.services.nginx.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aangine-platform-nginx-nossl.fullname" . }}-external-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aangine-platform-nginx-nossl.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.services.aangineNginxNodePort }}
      targetPort: {{ .Values.services.aangineNginxNodePort }}
      protocol: TCP
      name: http-port
  selector:
    {{- include "aangine-platform-nginx-nossl.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.nginx.hostname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aangine-platform-nginx-nossl.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.services.aangineNginxNodePort }}
      targetPort: {{ .Values.services.aangineNginxNodePort }}
      protocol: TCP
      name: http-port
  selector:
    {{- include "aangine-platform-nginx-nossl.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
