{{- if .Values.services.commander.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aangine-system-commander.fullname" . }}-cfg-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aangine-system-commander.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.commander.replicaCount }}
  selector:
    matchLabels:
      {{- include "aangine-system-commander.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "aangine-system-commander.fullname" . }}-deployment-template
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/hostname: {{ .Values.services.commander.hostname }}
        {{- include "aangine-system-commander.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    {{- toYaml .Values.services.affinityNodes | nindent 20 }}
    {{- with .Values.services.commander.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "aangine-system-commander.serviceAccountName" . }}
      {{- if (.Values.services.subdomain) }}
      subdomain: {{ .Values.services.subdomain }}
      {{- end }}
      restartPolicy: {{ .Values.services.commander.restartPolicy }}
      securityContext:
        {{- toYaml .Values.services.commander.podSecurityContext | nindent 8 }}
      volumes:
        - name: commander-host-dir
          hostPath:
            path: {{ .Values.services.commander.storage.hostConfigFolder }}
      hostname: {{ .Values.services.commander.hostname }}
      hostAliases:
        - ip: {{ .Values.services.mongoDbIp }}
          hostnames:
            - aangine-db
            {{- if (.Values.services.subdomain) }}
            - aangine-db.{{ .Values.services.subdomain }}.{{ .Release.Namespace }}.svc.cluster.local
            {{- else }}
            - aangine-db.{{ .Release.Namespace }}.svc.cluster.local
            {{- end }}
            - aangine-db.local
        - ip: 127.0.0.1
          hostnames:
            - {{ .Values.services.commander.hostname }}.local
            - localhost.local
            - localhost
      containers:
        - name: {{ .Values.services.commander.containerName }}
          securityContext:
            {{- toYaml .Values.services.commander.securityContext | nindent 12 }}
          image: {{ printf "%s/%s:%s" .Values.services.commander.image.repository .Values.services.commander.image.repositoryBranch .Values.services.commander.image.repositoryTag | quote}}
          imagePullPolicy: {{ .Values.services.commander.image.pullPolicy }}
          command: 
            {{- toYaml .Values.services.commander.commands | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - cat
                - /docker-entrypoint.sh
          readinessProbe:
            exec:
              command:
                - cat
                - /docker-entrypoint.sh
          resources:
            {{- toYaml .Values.services.commander.resources | nindent 12 }}
          volumeMounts:
            - name: commander-host-dir
              mountPath: /mnt/sda
            
      {{- with .Values.services.commander.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.services.commander.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.services.commander.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
