# Aangine AddsOn Config default values file
services:
  subdomain: aangine
  affinityNodes: []
  addson_config:
    create: false
    hostname: addson-config
    stackPrefix: aangine
    stackName: aangine-platform
    stackDescrition: Aangine
    applicationName: addson-config
    replicaCount: 1
    containerName: addson-config-internal
    privilegedPorts:
    image:
      repository: registry.gitlab.com/aangine/kubernetes/aangine-k8s-addson-config
      repositoryBranch: qa
      repositoryTag: latest
      pullPolicy: IfNotPresent
    storage:
      hostConfigFolder: /home/docker
    imagePullSecrets: 
      - name: aanginesecret
    nameOverride: ""
    fullnameOverride: ""
    restartPolicy: Always
    podSecurityContext: {}

      #privileged: true
      # fsGroup: 2000
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
    commands:
      - "/docker-entrypoint.sh"
      - "clone"
      - "git@gitlab.com:aangine/kubernetes/kubernetes-aangine-charts-config.git"
      - "master"
      - "^^^"
      - "script"
      - "/root/repo/kubernetes-aangine-charts-config"
      - "/root/repo/kubernetes-aangine-charts-config/execute-config.sh"
      - "/mnt/disk/kubernetes/config"
      - "^^^"
      - "sleep"
      - "infinity"
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: aangine-service-account

