#Consul Single Instance default values file
services:
  subdomain: aangine
  affinityNodes: []
  consulWrokerNodeIps: []
  dnsPolicy: ClusterFirst
  consul:
    cluster:
      create: true
    hostname: consul-public
    hostnames: consul-public
    stackPrefix: aangine
    stackName: aangine-platform
    stackDescrition: Aangine
    applicationName: consul
    replicaCount: 3
    containerName: consul-public
    privilegedPorts: "true"
    image:
      repository: registry.gitlab.com/aangine/kubernetes/aangine-service-docker-images/consul
      repositoryBranch: qa
      repositoryTag: latest
      pullPolicy: IfNotPresent
    storage:
      enableVolume: true
      installVolume: true
      capacity: 5Gi
      accessModes:
        - ReadWriteMany
      pvrp: Retain
      mountPoint: /mnt/sda
      hostDataBaseFolder: /mnt/sda
      hostConfigFolder: /home/docker/kubernetes/config/platform/consul/cluster
    imagePullSecrets: 
      - name: aanginesecret
    nameOverride: ""
    fullnameOverride: ""
    restartPolicy: Always
    podSecurityContext: {}

      # fsGroup: 2000
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
    service:
      enabled: true
      type: LoadBalancer
    commands: []
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: aangine-service-account

