{{- if .Values.services.mongodb.create -}}
{{- if .Values.services.mongodb.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.mongodb.hostname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aangine-databasemongodb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.services.mongodb.service.httpPort }}
      targetPort: {{ .Values.services.mongodb.service.httpPort }}
      protocol: TCP
      name: mongo-tcp-port
  selector:
    {{- include "aangine-databasemongodb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aangine-databasemongodb.fullname" . }}-external-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aangine-databasemongodb.labels" . | nindent 4 }}
spec:
  #clusterIP: {{ .Values.services.mongoDbIp }}
  type: {{ .Values.services.mongodb.service.type }}
  ports:
    - port: {{ .Values.services.MongoDbPort }}
      targetPort: {{ .Values.services.mongodb.service.httpPort }}
      protocol: TCP
      name: mongo-tcp-port
  selector:
    {{- include "aangine-databasemongodb.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
