# Aangine AddsOn Config default values file
services:
  subdomain: aangine
  affinityNodes: []
  productionInstance: false
  service_account:
    create: true
    hostname: service-account
    stackPrefix: aangine
    stackName: aangine-platform
    stackDescrition: Aangine
    applicationName: service-account
    containerName: addson-service-account-internal
    privilegedPorts:
    image:
      repository: busybox
      repositoryTag: latest
      pullPolicy: IfNotPresent
    storage:
      hostConfigFolder: /mnt
    imagePullSecrets: 
      - name: aanginesecret
    enableMongoDbHosts: true
    nameOverride: ""
    fullnameOverride: ""
    restartPolicy: Always
    podSecurityContext: {}

      #privileged: true
      # fsGroup: 2000
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
    commands:
      - "sleep"
      - "100000d"
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: aangine-service-account
  secrets:
  - name: aanginesecret

