{{- if .Values.services.aangine_ui.create -}}
{{- $svcHttpPort := .Values.services.aangine_ui.service.httpPort -}}
{{- $httpPort := .Values.services.aangine_ui.service.publicHttpPort -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aangine-frontend-aangine-ui.fullname" . }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aangine-frontend-aangine-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.services.aangine_ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "aangine-frontend-aangine-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "aangine-frontend-aangine-ui.fullname" . }}-deployment-template
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/hostname: {{ .Values.services.aangine_ui.hostname }}
        {{- include "aangine-frontend-aangine-ui.selectorLabels" . | nindent 8 }}
    spec:
      dnsPolicy: {{ .Values.services.dnsPolicy }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    {{- toYaml .Values.services.affinityNodes | nindent 20 }}
    {{- with .Values.services.aangine_ui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "aangine-frontend-aangine-ui.serviceAccountName" . }}
      {{- if (.Values.services.subdomain) }}
      subdomain: {{ .Values.services.subdomain }}
      {{- end }}
      restartPolicy: {{ .Values.services.aangine_ui.restartPolicy }}
      securityContext:
        {{- toYaml .Values.services.aangine_ui.podSecurityContext | nindent 8 }}
      hostname: {{ .Values.services.aangine_ui.hostname }}
      hostAliases:
        - ip: {{ .Values.services.mongoDbIp }}
          hostnames:
            - aangine-db
            {{- if (.Values.services.subdomain) }}
            - aangine-db.{{ .Values.services.subdomain }}.{{ .Release.Namespace }}.svc.cluster.local
            {{- else }}
            - aangine-db.{{ .Release.Namespace }}.svc.cluster.local
            {{- end }}
            - aangine-db.local
        - ip: 127.0.0.1
          hostnames:
            - {{ .Values.services.aangine_ui.hostname }}.local
            - localhost.local
            - localhost
      containers:
        - name: {{ .Values.services.aangine_ui.containerName }}
          securityContext:
            {{- toYaml .Values.services.aangine_ui.securityContext | nindent 12 }}
          image: {{ printf "%s/%s:%s" .Values.services.aangine_ui.image.repository .Values.services.aangine_ui.image.repositoryBranch .Values.services.aangine_ui.image.repositoryTag | quote}}
          imagePullPolicy: {{ .Values.services.aangine_ui.image.pullPolicy }}
          ports:
            - name: http-port
              containerPort:  {{ $svcHttpPort }}
              protocol: TCP
          env:
            {{- toYaml .Values.services.aangine_ui.environment | nindent 12 }}
#          livenessProbe:
#            httpGet:
#              path: /
#              port: {{ $svcHttpPort }}
#            initialDelaySeconds: 10
#            timeoutSeconds: 10
#            successThreshold: 1
#            periodSeconds: 300
#            failureThreshold: 20
#          readinessProbe:
#            httpGet:
#              path: /
#              port: {{ $svcHttpPort }}
#            initialDelaySeconds: 10
#            timeoutSeconds: 10
#            successThreshold: 1
#            periodSeconds: 300
#            failureThreshold: 20
          resources:
            {{- toYaml .Values.services.aangine_ui.resources | nindent 12 }}
      {{- with .Values.services.aangine_ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.services.aangine_ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.services.aangine_ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
