{{- if .Values.services.aangine_ui.create -}}
{{- if .Values.services.aangine_ui.service.enabled -}}
{{- $svcHttpPort := .Values.services.aangine_ui.service.httpPort -}}
{{- $httpPort := .Values.services.aangine_ui.service.publicHttpPort -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.aangine_ui.hostname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aangine-frontend-aangine-ui.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ $svcHttpPort }}
      targetPort: {{ $svcHttpPort }}
      protocol: TCP
      name: http-port
  selector:
    {{- include "aangine-frontend-aangine-ui.selectorLabels" . | nindent 4 }}

{{- end }}
{{- end }}
