{{- if .Values.services.local_volume_provisioner.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aangine-system-local-volume-provisioner.clusterRoleBindingName" . }}
  labels:
    {{- include "aangine-system-local-volume-provisioner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aangine-system-local-volume-provisioner.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "aangine-system-local-volume-provisioner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

