{{- if .Values.services.local_volume_provisioner.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aangine-system-local-volume-provisioner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aangine-system-local-volume-provisioner.labels" . | nindent 4 }}
{{- end }}

