{{- if .Values.services.service_account.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aangine-system-service-account.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aangine-system-service-account.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.serviceAccount.secrets }}
secrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}